name: CI Deploy Workflow

on:
  workflow_run:
    workflows: ["CI Test Workflow"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prijava v Docker
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server image
        run: |
          docker build -f server/.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/sa-server:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sa-server:latest

      - name: Build and push client image
        run: |
          docker build -f client/.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/sa-client:latest ./client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sa-client:latest
