name: CI Test Workflow

on:
  push:
    branches: [main]

jobs:
  check_tests:
    runs-on: self-hosted
    outputs:
      test_status: ${{ steps.check.outputs.exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for test scripts
        id: check
        run: |
          if [ -d "tests" ] && ls tests/test_*.py 1> /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Test scripts missing." > napaka.txt
          fi

      - name: Upload napaka.txt
        if: steps.check.outputs.exists == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  run_tests:
    needs: check_tests
    if: needs.check_tests.outputs.test_status == 'true'
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r server/requirements.txt pytest

      - name: Run tests
        run: |
          pytest tests
